### ISSUE TITLE
Counterparty transactions

### ISSUE THREAD

**Issue by unsystemizer** [RCasatta/op_return#2]
It'd be nice to have them added. 
A decoder is available here:
https://github.com/tokenly/counterparty-transaction-parser

**Comment by RCasatta** [comment]
It looks not so easy to understand logics and integrate...
Any parser available in Java?

**Comment by unsystemizer** [comment]
Unfortunately it seems none. Would JavaScript be of interest?

**Comment by RCasatta** [comment]
The way the code actually works is by analyzing first bytes of op_return. There are other way of implementing protocols on bitcoin and that's apparently the way Counterparty works because there are just 36 txs that has CNTPRTY as op_return begin data. It's not my objective right now to dig in the specific counterparty case to recognize counterparty txs. I am surely interested to merge eventual external commit that recognize counterparty and other "not op_return only protocol".
So, thanks but JavaScript is not of interest right now
